export const docsRedirects = new Map<string, string>([
  ["installation/windows", "/docs/start-here/windows"],
  ["installation/macos", "/docs/start-here/macos"],
  ["installation/linux", "/docs/start-here/linux"],
  ["installation/dedicated-server", "/docs/start-here/dedicated-server"],
  ["guides/gui-mode", "/docs/start-here/gui-mode"],
  ["guides/cli-mode", "/docs/start-here/cli-mode"],
  ["guides/gui-navigation", "/docs/how-to/gui-navigation"],
  ["guides/docker", "/docs/how-to/docker"],
  ["guides/webdav", "/docs/how-to/webdav"],
  ["guides/mcp", "/docs/how-to/mcp"],
  ["guides/dedicated-mode", "/docs/how-to/dedicated-mode"],
  ["usage/accounts", "/docs/how-to/import-accounts"],
  ["usage/proxies", "/docs/how-to/import-proxies"],
  ["usage/account-formats", "/docs/reference/account-formats"],
  ["usage/proxy-formats", "/docs/reference/proxy-formats"],
  ["usage/versions", "/docs/reference/versions"],
  ["usage/commands", "/docs/reference/commands"],
  ["usage/cli-flags", "/docs/reference/cli-flags"],
  ["usage/operation-modes", "/docs/concepts/operation-modes"],
  ["usage/plugins", "/docs/concepts/plugins"],
  ["terminology", "/docs/reference/terminology"],
  ["installation", "/docs/start-here"],
  ["guides", "/docs/how-to"],
  ["usage", "/docs/reference"],
]);
