/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as GithubRouteImport } from './routes/github'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DocsDotmdxRouteImport } from './routes/docs[.]mdx'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as DemoVideoRouteImport } from './routes/demo-video'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as GetProxiesIndexRouteImport } from './routes/get-proxies/index'
import { Route as GetAccountsIndexRouteImport } from './routes/get-accounts/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as GetProxiesSlugRouteImport } from './routes/get-proxies/$slug'
import { Route as GetAccountsSlugRouteImport } from './routes/get-accounts/$slug'
import { Route as DocsChar123Char125DotmdxRouteImport } from './routes/docs/{$}[.]mdx'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogFeedDotxmlRouteImport } from './routes/blog/feed[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as AccountPathRouteImport } from './routes/account/$path'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotmdxRoute = DocsDotmdxRouteImport.update({
  id: '/docs.mdx',
  path: '/docs.mdx',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoVideoRoute = DemoVideoRouteImport.update({
  id: '/demo-video',
  path: '/demo-video',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetProxiesIndexRoute = GetProxiesIndexRouteImport.update({
  id: '/get-proxies/',
  path: '/get-proxies/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAccountsIndexRoute = GetAccountsIndexRouteImport.update({
  id: '/get-accounts/',
  path: '/get-accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GetProxiesSlugRoute = GetProxiesSlugRouteImport.update({
  id: '/get-proxies/$slug',
  path: '/get-proxies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAccountsSlugRoute = GetAccountsSlugRouteImport.update({
  id: '/get-accounts/$slug',
  path: '/get-accounts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdxRoute =
  DocsChar123Char125DotmdxRouteImport.update({
    id: '/docs/{$}.mdx',
    path: '/docs/{$}.mdx',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogFeedDotxmlRoute = BlogFeedDotxmlRouteImport.update({
  id: '/blog/feed.xml',
  path: '/blog/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPathRoute = AccountPathRouteImport.update({
  id: '/account/$path',
  path: '/account/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/demo-video': typeof DemoVideoRoute
  '/discord': typeof DiscordRoute
  '/docs.mdx': typeof DocsDotmdxRoute
  '/donate': typeof DonateRoute
  '/download': typeof DownloadRoute
  '/github': typeof GithubRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/$path': typeof AccountPathRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/$path': typeof AuthPathRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.mdx': typeof DocsChar123Char125DotmdxRoute
  '/get-accounts/$slug': typeof GetAccountsSlugRoute
  '/get-proxies/$slug': typeof GetProxiesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/get-accounts/': typeof GetAccountsIndexRoute
  '/get-proxies/': typeof GetProxiesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/demo-video': typeof DemoVideoRoute
  '/discord': typeof DiscordRoute
  '/docs.mdx': typeof DocsDotmdxRoute
  '/donate': typeof DonateRoute
  '/download': typeof DownloadRoute
  '/github': typeof GithubRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/$path': typeof AccountPathRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/$path': typeof AuthPathRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.mdx': typeof DocsChar123Char125DotmdxRoute
  '/get-accounts/$slug': typeof GetAccountsSlugRoute
  '/get-proxies/$slug': typeof GetProxiesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/get-accounts': typeof GetAccountsIndexRoute
  '/get-proxies': typeof GetProxiesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/demo-video': typeof DemoVideoRoute
  '/discord': typeof DiscordRoute
  '/docs.mdx': typeof DocsDotmdxRoute
  '/donate': typeof DonateRoute
  '/download': typeof DownloadRoute
  '/github': typeof GithubRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/$path': typeof AccountPathRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/$path': typeof AuthPathRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.mdx': typeof DocsChar123Char125DotmdxRoute
  '/get-accounts/$slug': typeof GetAccountsSlugRoute
  '/get-proxies/$slug': typeof GetProxiesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/get-accounts/': typeof GetAccountsIndexRoute
  '/get-proxies/': typeof GetProxiesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/demo-video'
    | '/discord'
    | '/docs.mdx'
    | '/donate'
    | '/download'
    | '/github'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/account/$path'
    | '/api/reviews'
    | '/api/search'
    | '/auth/$path'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/docs/$'
    | '/docs/{$}.mdx'
    | '/get-accounts/$slug'
    | '/get-proxies/$slug'
    | '/resources/$slug'
    | '/blog/'
    | '/get-accounts/'
    | '/get-proxies/'
    | '/resources/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/demo-video'
    | '/discord'
    | '/docs.mdx'
    | '/donate'
    | '/download'
    | '/github'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/account/$path'
    | '/api/reviews'
    | '/api/search'
    | '/auth/$path'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/docs/$'
    | '/docs/{$}.mdx'
    | '/get-accounts/$slug'
    | '/get-proxies/$slug'
    | '/resources/$slug'
    | '/blog'
    | '/get-accounts'
    | '/get-proxies'
    | '/resources'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/cookie-policy'
    | '/demo-video'
    | '/discord'
    | '/docs.mdx'
    | '/donate'
    | '/download'
    | '/github'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/account/$path'
    | '/api/reviews'
    | '/api/search'
    | '/auth/$path'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/docs/$'
    | '/docs/{$}.mdx'
    | '/get-accounts/$slug'
    | '/get-proxies/$slug'
    | '/resources/$slug'
    | '/blog/'
    | '/get-accounts/'
    | '/get-proxies/'
    | '/resources/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DemoVideoRoute: typeof DemoVideoRoute
  DiscordRoute: typeof DiscordRoute
  DocsDotmdxRoute: typeof DocsDotmdxRoute
  DonateRoute: typeof DonateRoute
  DownloadRoute: typeof DownloadRoute
  GithubRoute: typeof GithubRoute
  ImprintRoute: typeof ImprintRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AccountPathRoute: typeof AccountPathRoute
  ApiReviewsRoute: typeof ApiReviewsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  AuthPathRoute: typeof AuthPathRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogFeedDotxmlRoute: typeof BlogFeedDotxmlRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdxRoute: typeof DocsChar123Char125DotmdxRoute
  GetAccountsSlugRoute: typeof GetAccountsSlugRoute
  GetProxiesSlugRoute: typeof GetProxiesSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GetAccountsIndexRoute: typeof GetAccountsIndexRoute
  GetProxiesIndexRoute: typeof GetProxiesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs.mdx': {
      id: '/docs.mdx'
      path: '/docs.mdx'
      fullPath: '/docs.mdx'
      preLoaderRoute: typeof DocsDotmdxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-video': {
      id: '/demo-video'
      path: '/demo-video'
      fullPath: '/demo-video'
      preLoaderRoute: typeof DemoVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-proxies/': {
      id: '/get-proxies/'
      path: '/get-proxies'
      fullPath: '/get-proxies/'
      preLoaderRoute: typeof GetProxiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-accounts/': {
      id: '/get-accounts/'
      path: '/get-accounts'
      fullPath: '/get-accounts/'
      preLoaderRoute: typeof GetAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-proxies/$slug': {
      id: '/get-proxies/$slug'
      path: '/get-proxies/$slug'
      fullPath: '/get-proxies/$slug'
      preLoaderRoute: typeof GetProxiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-accounts/$slug': {
      id: '/get-accounts/$slug'
      path: '/get-accounts/$slug'
      fullPath: '/get-accounts/$slug'
      preLoaderRoute: typeof GetAccountsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.mdx': {
      id: '/docs/{$}.mdx'
      path: '/docs/{$}.mdx'
      fullPath: '/docs/{$}.mdx'
      preLoaderRoute: typeof DocsChar123Char125DotmdxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/feed.xml': {
      id: '/blog/feed.xml'
      path: '/blog/feed.xml'
      fullPath: '/blog/feed.xml'
      preLoaderRoute: typeof BlogFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$path': {
      id: '/account/$path'
      path: '/account/$path'
      fullPath: '/account/$path'
      preLoaderRoute: typeof AccountPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DemoVideoRoute: DemoVideoRoute,
  DiscordRoute: DiscordRoute,
  DocsDotmdxRoute: DocsDotmdxRoute,
  DonateRoute: DonateRoute,
  DownloadRoute: DownloadRoute,
  GithubRoute: GithubRoute,
  ImprintRoute: ImprintRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AccountPathRoute: AccountPathRoute,
  ApiReviewsRoute: ApiReviewsRoute,
  ApiSearchRoute: ApiSearchRoute,
  AuthPathRoute: AuthPathRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogFeedDotxmlRoute: BlogFeedDotxmlRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdxRoute: DocsChar123Char125DotmdxRoute,
  GetAccountsSlugRoute: GetAccountsSlugRoute,
  GetProxiesSlugRoute: GetProxiesSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GetAccountsIndexRoute: GetAccountsIndexRoute,
  GetProxiesIndexRoute: GetProxiesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
